service: dynamodb-crud-API

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
     DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}



custom:
  postsTableName: posts-table-${self:provider.stage}


plugins:
  -serverless-iam-roles-per-function


functions:
  getPost:
    handler: api.getPost
    name: get-post
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: post/{postId}
          method: GET

    iam:
       role:
        statements:
         - Effect: "Allow"
           Action:
             - "dynamodb:UpdateItem"
           Resource: !GetAtt PostsTable.Arn
  createPost:
     handler: api.createPost
     name: create-post
     memorySize: 128
     timeout: 5
     events:
       - http:
           path: post
           method: POST
     iam:
       role:
        statements:
         - Effect: "Allow"
           Action:
             - "dynamodb:PutItem"
           Resource: !GetAtt PostsTable.Arn


  updatePost:
     handler: api.updatePost
     name: update-post
     memorySize: 128
     timeout: 5
     events:
       - http:
           path: post/{postId}
           method: PUT
     iam:
       role:
        statements:
         - Effect: "Allow"
           Action:
             - "dynamodb:UpdateItem"
           Resource: !GetAtt PostsTable.Arn

  DeletePost:
     handler: api.DeletePost
     name: delete-post
     memorySize: 128
     timeout: 5
     events:
       - http:
           path: post/{postId}
           method: DELETE
     iam:
       role:
        statements:
         - Effect: "Allow"
           Action:
             - "dynamodb:DeleteItem"
           Resource: !GetAtt PostsTable.Arn
  getAllPosts:
     handler: api.getAllPosts
     name: get-all-posts
     memorySize: 128
     timeout: 5
     events:
       - http:
           path: posts
           method: GET
     iam:
       role:
        statements:
         - Effect: "Allow"
           Action:
             - "dynamodb:Scan"
           Resource: !GetAtt PostsTable.Arn





resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributesDefinitions:
          - AttributeName: postId
            AttributeType: S
        Keyschema:
          - AttributeName: postId 
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1